# SDDM Astronaut theme
# Instalar el theme: paru -S sddm-theme-astronaut
# Habilitar SDDM: sudo systemctl enable sddm
# Copiar este archivo: sudo install -m 0644 dotfiles/sddm/etc/sddm.conf.d/theme.conf /etc/sddm.conf.d/

[Theme]
Current=sddm-astronaut-theme
CursorTheme=Adwaita
Font=JetBrainsMono Nerd Font

[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell
InputMethod=
