# windowrulev2 — reglas por clase/título

# Scratchpad Claude
windowrulev2 = float,         class:^(kitty-claude)$
windowrulev2 = size 1100 700, class:^(kitty-claude)$
windowrulev2 = center,        class:^(kitty-claude)$
windowrulev2 = workspace special:claude silent, class:^(kitty-claude)$

# Diálogos comunes
windowrulev2 = float, class:^(pavucontrol|blueman-manager|nm-connection-editor)$
windowrulev2 = float, title:^(Open File|Save File|Save As)$
windowrulev2 = float, class:^(xdg-desktop-portal-gtk)$

# Gaming — tearing libre + sin animaciones
windowrulev2 = immediate,        class:^(steam_app_).*
windowrulev2 = immediate,        class:^(gamescope)$
windowrulev2 = fullscreen,       class:^(gamescope)$
windowrulev2 = noanim,           class:^(steam_app_).*
windowrulev2 = noblur,           class:^(steam_app_).*
windowrulev2 = noshadow,         class:^(steam_app_).*
windowrulev2 = idleinhibit fullscreen, class:^(steam_app_).*
windowrulev2 = idleinhibit fullscreen, class:^(gamescope)$
windowrulev2 = workspace 7,      class:^(steam)$
windowrulev2 = workspace 8,      class:^(lutris)$

# Picture-in-Picture
windowrulev2 = float,            title:^(Picture-in-Picture)$
windowrulev2 = pin,              title:^(Picture-in-Picture)$

# Layer rules
layerrule = blur, waybar
layerrule = blur, rofi
layerrule = blur, swaync-control-center
layerrule = blur, swaync-notification-window
