# Hyprpaper — wallpapers
# El script wallpaper-cycle.sh sustituye dinámicamente esta config.
# Para inicio, define aquí uno por defecto.

# preload  = ~/Pictures/wallpapers/default.jpg
# wallpaper = ,~/Pictures/wallpapers/default.jpg

ipc = on
splash = false
